// <auto-generated />
using System;
using FinanceSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceSystem.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260604075013_AddCashFlowHistory")]
    partial class AddCashFlowHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceSystem.Models.Entities.AmortizationRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("EarlyRepaymentPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("InterestPayment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("IsEarlyRepayment")
                        .HasColumnType("bit");

                    b.Property<int>("LoanInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalPayment")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("LoanInfoId");

                    b.ToTable("AmortizationRows");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.CashFlowEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CashFlowEntries");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.CashFlowHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<int>("EntryCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasDeficit")
                        .HasColumnType("bit");

                    b.Property<decimal>("IRR")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("InitialInvestment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("NPV")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("NetCashFlow")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("PeriodCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInflow")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TotalOutflow")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CashFlowHistories");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.InterestRateTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualRatePercent")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TermLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("InterestRateTables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            AnnualRatePercent = 2.5m,
                            Note = "",
                            ProductType = "SavingDeposit",
                            RateType = "Savings",
                            TermLabel = "1 tháng",
                            TermMonths = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            AnnualRatePercent = 3.0m,
                            Note = "",
                            ProductType = "SavingDeposit",
                            RateType = "Savings",
                            TermLabel = "3 tháng",
                            TermMonths = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            AnnualRatePercent = 4.5m,
                            Note = "",
                            ProductType = "SavingDeposit",
                            RateType = "Savings",
                            TermLabel = "6 tháng",
                            TermMonths = 6,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            AnnualRatePercent = 4.7m,
                            Note = "",
                            ProductType = "SavingDeposit",
                            RateType = "Savings",
                            TermLabel = "9 tháng",
                            TermMonths = 9,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            AnnualRatePercent = 5.2m,
                            Note = "",
                            ProductType = "SavingDeposit",
                            RateType = "Savings",
                            TermLabel = "12 tháng",
                            TermMonths = 12,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            AnnualRatePercent = 5.5m,
                            Note = "",
                            ProductType = "SavingDeposit",
                            RateType = "Savings",
                            TermLabel = "18 tháng",
                            TermMonths = 18,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            AnnualRatePercent = 5.7m,
                            Note = "",
                            ProductType = "SavingDeposit",
                            RateType = "Savings",
                            TermLabel = "24 tháng",
                            TermMonths = 24,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            AnnualRatePercent = 6.0m,
                            Note = "Khóa hạn",
                            ProductType = "SavingDeposit",
                            RateType = "Savings",
                            TermLabel = "36 tháng",
                            TermMonths = 36,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-0000-0000-000000000001"),
                            AnnualRatePercent = 14.0m,
                            Note = "Không cần tài sản bảo đảm",
                            ProductType = "UnsecuredLoan",
                            RateType = "Loan",
                            TermLabel = "Vay tín chấp",
                            TermMonths = 36,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-0000-0000-000000000002"),
                            AnnualRatePercent = 16.0m,
                            Note = "Tính lãi trên số tiền đã sử dụng",
                            ProductType = "OverdraftLoan",
                            RateType = "Loan",
                            TermLabel = "Vay thấu chi",
                            TermMonths = 12,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("b2000000-0000-0000-0000-000000000003"),
                            AnnualRatePercent = 10.5m,
                            Note = "Trả góp định kỳ",
                            ProductType = "InstallmentLoan",
                            RateType = "Loan",
                            TermLabel = "Vay trả góp",
                            TermMonths = 60,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.InvestmentProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CashFlows")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("InitialInvestment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("InvestmentProjects");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.LoanInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("EarlyRepaymentPenaltyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,6)")
                        .HasDefaultValue(0.02m);

                    b.Property<int?>("EarlyRepaymentPeriod")
                        .HasColumnType("int");

                    b.Property<bool>("IsEarlyRepayment")
                        .HasColumnType("bit");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("ServiceFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TermCount")
                        .HasColumnType("int");

                    b.Property<int>("TermUnit")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("LoanInfos");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.OverdraftLoanInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OverdraftLoanInfos");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.OverdraftUsageEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualInterestRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,6)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OverdraftLoanInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UsedAmount")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("OverdraftLoanInfoId");

                    b.ToTable("OverdraftUsageEntries");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("AnnualRatePercent")
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.UserActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SavingsInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("DemandInterestRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,6)")
                        .HasDefaultValue(0.001m);

                    b.Property<DateTime>("DepositDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EarlyWithdrawAtMonth")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SavingsInfos");
                });

            modelBuilder.Entity("SavingsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("InterestEarned")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("InterestPaid")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("IsEarlyWithdraw")
                        .HasColumnType("bit");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SavingsInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SavingsInfoId");

                    b.ToTable("SavingsRows");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.AmortizationRow", b =>
                {
                    b.HasOne("FinanceSystem.Models.Entities.LoanInfo", "Loan")
                        .WithMany("Schedule")
                        .HasForeignKey("LoanInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.OverdraftUsageEntry", b =>
                {
                    b.HasOne("FinanceSystem.Models.Entities.OverdraftLoanInfo", "OverdraftLoan")
                        .WithMany("UsageEntries")
                        .HasForeignKey("OverdraftLoanInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OverdraftLoan");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.ServiceRequest", b =>
                {
                    b.HasOne("FinanceSystem.Models.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.UserActivityLog", b =>
                {
                    b.HasOne("FinanceSystem.Models.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.UserRole", b =>
                {
                    b.HasOne("FinanceSystem.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceSystem.Models.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SavingsRow", b =>
                {
                    b.HasOne("SavingsInfo", null)
                        .WithMany()
                        .HasForeignKey("SavingsInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.LoanInfo", b =>
                {
                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.OverdraftLoanInfo", b =>
                {
                    b.Navigation("UsageEntries");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
