// <auto-generated />
using FinanceSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceSystem.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260528000625_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceSystem.Models.Entities.AmortizationRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("EarlyRepaymentPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("InterestPayment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("IsEarlyRepayment")
                        .HasColumnType("bit");

                    b.Property<int>("LoanInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalPayment")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("LoanInfoId");

                    b.ToTable("AmortizationRows");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.CashFlowEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CashFlowEntries");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.InvestmentProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CashFlows")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("InitialInvestment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("InvestmentProjects");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.LoanInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("EarlyRepaymentPenaltyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,6)")
                        .HasDefaultValue(0.02m);

                    b.Property<int?>("EarlyRepaymentPeriod")
                        .HasColumnType("int");

                    b.Property<bool>("IsEarlyRepayment")
                        .HasColumnType("bit");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("ServiceFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TermCount")
                        .HasColumnType("int");

                    b.Property<int>("TermUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoanInfos");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.AmortizationRow", b =>
                {
                    b.HasOne("FinanceSystem.Models.Entities.LoanInfo", "Loan")
                        .WithMany("Schedule")
                        .HasForeignKey("LoanInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("FinanceSystem.Models.Entities.LoanInfo", b =>
                {
                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
